const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{varVida: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Garoto: 0},
	{Sólido: 0},
	{Chão_Sólido: 0},
	{Teclado: 0},
	{Céu: 0},
	{Monstro: 0},
	{Grama: 0},
	{Árvore: 0},
	{Placa: 0},
	{var_largura: 0},
	{var_inicial: 0},
	{var_tamanho: 0},
	{barra: 0},
	{Fixar: 0},
	{títuloVida: 0},
	{Base: 0},
	{Chão: 0},
	{Pedra: 0},
	{Moeda: 0},
	{textoMoeda: 0},
	{Sprite: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Texto2: 0},
	{Sprite4: 0},
	{vitoria: 0},
	{capa: 0},
	{jogar: 0},
	{Mouse: 0},
	{TXTVITORIA: 0},
	{varMoeda: 0}
];

self.InstanceType = {
	Garoto: class extends self.ISpriteInstance {},
	Chão_Sólido: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Céu: class extends self.ITiledBackgroundInstance {},
	Monstro: class extends self.ISpriteInstance {},
	Grama: class extends self.ISpriteInstance {},
	Árvore: class extends self.ISpriteInstance {},
	Placa: class extends self.ISpriteInstance {},
	barra: class extends self.ISpriteInstance {},
	títuloVida: class extends self.ITextInstance {},
	Base: class extends self.ISpriteInstance {},
	Chão: class extends self.ITiledBackgroundInstance {},
	Pedra: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	textoMoeda: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	vitoria: class extends self.ITextInstance {},
	capa: class extends self.ISpriteInstance {},
	jogar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TXTVITORIA: class extends self.ITextInstance {}
}